### PR TITLE
Voting

### PR DESCRIPTION
**Pull request by MrNesli**
I have messed up, as usual, with the other pull request.

### CODE REVIEW

**Comment by MrNesli** [comment]
I don't know how to get rid of all those commits

**Comment by PenguinBoi12** [comment]
>  I don't know how to get rid of all those commits

It's ok, we don't care about the commits. At the end it's shipped as 1 whole commit.

**Comment by MrNesli** [comment]
How much time will the wordle take to be refactored :anguished:

**Review by PenguinBoi12 — APPROVED** [review]
There was again a few things to change. There was a lot of problems regarding the doc and the types. I also feel like you didn't test everything properly. There was some things not working super super well. 

Instead of sending it back, I've decided to fix the issues and do some adjustment to make the whole thing work a little bit better/be smoother. With that said, I mainly fixed your docstring. Please check them out to ensure your future comments are correct. I also removed most of the ones in the `poll_cog` since it was way to inconsistant with the rest of the file. 

To properly test the types you can use mypy. It's a library that Grace uses to ensure types correctness. You use it like this `mypy path/to/file`. It will show where you have type errors and what they are.

**Pull request merged**
